### PR TITLE
Core Drive Technologies (PID + ASAM)

### LINKED ISSUE #5: PID

### PR DESCRIPTION
**Pull request by ariporad**
Fixes #5, #6.

### CODE REVIEW

**Comment by michaelconnolly** [comment]
Walked through the code this evening.  Couple pieces of advice:

* one good practice for any new function is to also check in a test file that calls it, and checks that the right answer comes out.  This is probably not the most exciting thing to do (who wants to write test code when you can spend time writing new code!), but in general it's good hygiene.  Think about creating a "test" folder, and throwing in scripts that call some of your code with inputs that should give you a particular output.   As an example, look at ASAMCalculator.computeMotorPower().   You could have a test file that calls it 10 times with 10 different inputs, and verify that the output you get is what you expect. 

* I couldn't quite put my finger on it, but something seemed odd with the design of the PIDCalculator class.  I'm still getting the hang of this particular language, but it seems to have two major services it provides: "compute" and "give me a Tuning object".  But, "compute" requires that the a PIDCalculator object was created with the right initial target Angle.  Take my advice with a grain of salt, but maybe it would be more straightforward to just give a target angle as an additional parameter and just make "compute" a static function in a static class.  

* there are a couple cases where if you took one line of your existing code, and broke it into several lines, the code would be more readable by people who come after you.  Here's one example:

       controller.tuning = PIDCalculator.Tuning(configValues[ConfigValue.P] ?: 0.0, configValues[ConfigValue.I] ?: 0.0, configValues[ConfigValue.D] ?: 0.0, Double.POSITIVE_INFINITY)

Could be ...

var pValue : Double = configValues[ConfigValue.P] ?: 0.0
var iValue : Double = configValues[ConfigValue.I] ?: 0.0
var dValue : Double = configValues[ConfigValue.D] ?: 0.0
 controller.tuning = PIDCalculator.Tuning(pValue, iValue, dValue, Double.POSITIVE_INFINITY)

**Comment by ariporad** [comment]
@michaelconnolly Thanks for taking a look! In order:

* In general, we don't write unit tests because the FTC SDK *really* doesn't like to be run without a physical robot present. It's possible that we could get something pure and isolated like `ASAMCalculator` to do it, but in the past we haven't found it to be worth the effort.
* I think you might be misunderstanding the difference between `PIDCalculator` vs. `PIDController`. The idea is that `PIDCalculator` just contains pure math, and `PIDController` bridges that to the hardware. However, we use PID in a couple of different ways, so `PIDController` is extended by `StraightPIDController` and `TurningPIDController`, which do exactly what you think they do.
* `PIDCalculator` needs to be an instantiated class, because it needs to store state between calls to `compute`.
* Fair enough. I'll try to fix that when I have a moment.

**Comment by michaelconnolly** [comment]
Yes, unit tests are just a nice-to-have.   It might be useful in the latter stages of your project if you don't have confidence that your encapsulated helper classes like ASAMCalculator are 100% correct.

I understand the difference between PIDCalculator and PIDController, no worries there.  You answered my design question though; you designed it the way you did because it maintains state, which i hadn't notice (looks like "lastError" is the state you need to maintain).  

BTW, take a look at the 'do' look that starts on line 23 of your abstract PIDController class.  I don't know it is a bug or not, but because you initialize lastLoopTime = 0, the very first time you run through the loop, dTime will end up being a very large number.  The second time around it will correctly be a delta of time since the last loop pass.  What happens when dTime is a very large number when you call calculator.compute(..) near the end of the loop, during the first iteration of the loop?

**Comment by michaelconnolly** [comment]
Just taking a step back, answer the question, what do you wish dTime was the very first time you run the loop?

**Comment by zoecarver** [comment]
I _think_ it should be `1` (probably what it should be initialized as then 😄). But let's ask @ariporad .

**Comment by zoecarver** [comment]
@ariporad I thought it should be `1` so that we get [the error](https://github.com/redshiftrobotics/2856/pull/10/files#diff-b64fd78dfbb2709abb2530f2e1b037fcR20) all on its own. If its `0` then `I` will also be `0`.

**Pull request merged**
